name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
     - cron: '* */12 * * *'
jobs: 
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        Container: [0,1,2,3,4,5,6,7]
        Version: [0,1,2,3,4]
      fail-fast: false
    steps:
    - name: Run checkout@v2.3.4
      uses: actions/checkout@v2.3.4
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test
      run: |
        python test.py

        echo "done"
